"""
NEP Excellence Awards 2026 - College Domain Models
Defines first-class College Assessment sessions and audit logs.
"""
from datetime import date
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.authentication.models import College


class ImmutableCollegeRecordError(Exception):
    """Raised when an attempt is made to modify or delete an immutable audit record."""
    pass


class CollegeAssessment(models.Model):
    """
    Authoritative College Assessment session entity.
    Encapsulates institutional assessment metadata, statutory assessment window,
    and raw parameter inputs for C1–C22.
    """
    assessment_id = models.CharField(
        max_length=100,
        unique=True,
        db_index=True,
        help_text=_("Unique assessment identifier (e.g. ASSESS-2026-COL-001).")
    )
    college = models.ForeignKey(
        College,
        on_delete=models.CASCADE,
        related_name="assessments",
        help_text=_("College institution under assessment.")
    )
    framework = models.CharField(
        max_length=50,
        default="COLLEGE_2026",
        editable=False,
        db_index=True,
        help_text=_("Enforces framework isolation: COLLEGE_2026.")
    )
    academic_year = models.CharField(
        max_length=20,
        default="2025-26",
        help_text=_("Statutory academic year (2025-26).")
    )
    period_start = models.DateField(
        default=date(2025, 7, 1),
        help_text=_("Assessment window start date (1 July 2025).")
    )
    period_end = models.DateField(
        default=date(2026, 6, 30),
        help_text=_("Assessment window end date (30 June 2026).")
    )
    status = models.CharField(
        max_length=50,
        default="DRAFT",
        db_index=True,
        help_text=_("Lifecycle status: DRAFT, SUBMITTED, UNDER_REVIEW, CERTIFIED, REJECTED.")
    )
    submitted_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("Timestamp when assessment was formally submitted.")
    )
    parameter_data = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Structured raw parameter inputs for C1–C22.")
    )
    assigned_reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="assigned_college_assessments",
        help_text=_("Screening committee reviewer assigned to this assessment.")
    )
    certified_score = models.FloatField(
        null=True,
        blank=True,
        help_text=_("Authoritative final certified score generated by frozen scoring engine.")
    )
    certification_status = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Certification status: FINALIZABLE, BLOCKED, etc.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("College Assessment")
        verbose_name_plural = _("College Assessments")
        ordering = ["-created_at"]

    def __str__(self):
        return f"CollegeAssessment({self.assessment_id} - {self.college.name})"


class CollegeAssessmentAuditLog(models.Model):
    """
    Append-only audit trail for College assessment lifecycle changes.
    """
    log_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        db_index=True
    )
    assessment = models.ForeignKey(
        CollegeAssessment,
        on_delete=models.CASCADE,
        related_name="audit_logs",
        help_text=_("Associated College assessment.")
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="college_assessment_audit_events",
        help_text=_("Actor who initiated the assessment state change.")
    )
    action = models.CharField(
        max_length=50,
        db_index=True,
        help_text=_("Action executed (e.g. CREATED, PARAMETER_UPDATED, SUBMITTED).")
    )
    previous_state = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment status before the action.")
    )
    new_state = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment status after the action.")
    )
    reason = models.TextField(
        blank=True,
        default="",
        help_text=_("Optional rationale or note for the action.")
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when the audit event occurred.")
    )

    class Meta:
        verbose_name = _("College Assessment Audit Log")
        verbose_name_plural = _("College Assessment Audit Logs")
        ordering = ["-timestamp"]

    def __str__(self):
        return f"CollegeAuditLog({self.assessment.assessment_id} - {self.action})"

    def save(self, *args, **kwargs):
        if self.pk is not None:
            raise ImmutableCollegeRecordError("CollegeAssessmentAuditLog entries are append-only and cannot be modified.")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ImmutableCollegeRecordError("CollegeAssessmentAuditLog entries cannot be deleted.")


class CollegeReviewAction(models.TextChoices):
    START_REVIEW = "START_REVIEW", _("Start Review")
    COMPLETE_REVIEW = "COMPLETE_REVIEW", _("Complete Review")
    RETURN_FOR_CORRECTION = "RETURN_FOR_CORRECTION", _("Return For Correction")
    BLOCK_REVIEW = "BLOCK_REVIEW", _("Block Review")
    EVALUATE = "EVALUATE", _("Evaluate Scoring")
    CERTIFY = "CERTIFY", _("Certify Assessment")


class CollegeReviewRecord(models.Model):
    """
    Append-only historical record of committee review decisions and actions on a College Assessment.
    Guarantees that historical review outcomes, comments, and evaluation references are never overwritten.
    """
    review_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        db_index=True
    )
    assessment = models.ForeignKey(
        CollegeAssessment,
        on_delete=models.CASCADE,
        related_name="review_records",
        help_text=_("Associated College assessment.")
    )
    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="college_reviews",
        help_text=_("Committee reviewer or administrator who performed the review action.")
    )
    action = models.CharField(
        max_length=50,
        choices=CollegeReviewAction.choices,
        db_index=True,
        help_text=_("Action executed: START_REVIEW, COMPLETE_REVIEW, etc.")
    )
    status_before = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment lifecycle status prior to action.")
    )
    status_after = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment lifecycle status resulting from action.")
    )
    reason = models.TextField(
        blank=True,
        default="",
        help_text=_("Mandatory justification for corrections, blocks, or certification notes.")
    )
    comments = models.TextField(
        blank=True,
        default="",
        help_text=_("Reviewer notes or feedback for institution/committee.")
    )
    scoring_snapshot = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Authoritative snapshot of scoring evaluation at review time.")
    )
    evidence_readiness_snapshot = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Evidence readiness and coverage state snapshot at review time.")
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when the review action was logged.")
    )

    class Meta:
        verbose_name = _("College Review Record")
        verbose_name_plural = _("College Review Records")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["assessment", "created_at"]),
            models.Index(fields=["reviewer", "action"]),
        ]

    def __str__(self):
        return f"CollegeReviewRecord({self.assessment.assessment_id} - {self.action} by {self.reviewer.email})"

    def save(self, *args, **kwargs):
        if self.pk is not None:
            raise ImmutableCollegeRecordError("CollegeReviewRecord entries are append-only and cannot be modified.")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ImmutableCollegeRecordError("CollegeReviewRecord entries are audit logs and cannot be deleted.")

