"""
Writes the canonical parameter input schema (apps.scoring.field_schema) to the frontend as an ES module, so the
institution form submits exactly the field keys the backend validates and scores.

    python manage.py export_nep_schema
"""
import json
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from apps.evidence.taxonomy import get_subcriterion_contract
from apps.scoring.rules.definitions import COLLEGE_PARAMETERS, UNIVERSITY_PARAMETERS
from apps.scoring.policy import POLICY_ITEMS, RESOLVED, get_policy_state
from apps.scoring.field_schema import (
    ASSESSMENT_PERIOD_END,
    ASSESSMENT_PERIOD_START,
    COLLEGE_FIELD_SCHEMA,
    UNIVERSITY_FIELD_SCHEMA,
)

DEFAULT_OUTPUT = (
    Path(settings.BASE_DIR).parent / "Frontend" / "NEP_HARYANA_INT" / "src" / "utils" / "nepFrameworkSchema.generated.js"
)

HEADER = """// AUTO-GENERATED by `python manage.py export_nep_schema` from Backend/apps/scoring/field_schema.py.
// Do not edit by hand: change the backend schema and re-run the command.
"""


def _with_evidence_contracts(schema, framework):
    """Attach each subcriterion's evidence contract (apps.evidence.taxonomy) so the UI offers the right proof types."""
    rule_defs = COLLEGE_PARAMETERS if framework == "COLLEGE_2026" else UNIVERSITY_PARAMETERS
    out = {}
    for p_code, param in schema.items():
        subs = {}
        for s_code, sub in param["subcriteria"].items():
            c = get_subcriterion_contract(framework, p_code, s_code)
            sub = dict(sub)
            # Year-specific subcriteria (U4.A = 2024-25) only accept evidence tagged with that academic year
            sub["evidence_academic_year"] = rule_defs[p_code]["subcriteria"][s_code].get("evidence_academic_year")
            sub["evidence"] = None if c is None else {
                "status": getattr(c.status, "value", c.status),
                "canonical_type": c.canonical_evidence_type,
                "allowed_types": list(c.allowed_evidence_types),
                "documentary_requirement": c.source_documentary_requirement,
                "is_source_silent": c.is_source_silent,
                "is_unresolved": c.is_unresolved,
            }
            subs[s_code] = sub
        out[p_code] = {**param, "subcriteria": subs}
    return out


def _policy_notices():
    """Per-parameter notices for rubric questions the policy owner has not yet decided (apps.scoring.policy)."""
    notices = {}
    for item in POLICY_ITEMS.values():
        if get_policy_state(item.policy_id)["status"] == RESOLVED:
            continue
        for p_code in item.parameters:
            notices.setdefault(p_code, []).append(f"{item.question} Current handling: {item.implementation_default}")
    return {k: " ".join(v) for k, v in sorted(notices.items())}


class Command(BaseCommand):
    help = "Export the canonical NEP 2026 parameter input schema to the frontend."

    def add_arguments(self, parser):
        parser.add_argument("--output", default=str(DEFAULT_OUTPUT))

    def handle(self, *args, **options):
        out = Path(options["output"])
        body = [
            HEADER,
            f"export const ASSESSMENT_PERIOD_START = {json.dumps(ASSESSMENT_PERIOD_START)};",
            f"export const ASSESSMENT_PERIOD_END = {json.dumps(ASSESSMENT_PERIOD_END)};",
            "",
            f"export const POLICY_NOTICES = {json.dumps(_policy_notices(), indent=2, ensure_ascii=False)};",
            "",
            f"export const COLLEGE_FIELD_SCHEMA = {json.dumps(_with_evidence_contracts(COLLEGE_FIELD_SCHEMA, 'COLLEGE_2026'), indent=2, ensure_ascii=False)};",
            "",
            f"export const UNIVERSITY_FIELD_SCHEMA = {json.dumps(_with_evidence_contracts(UNIVERSITY_FIELD_SCHEMA, 'UNIVERSITY_2026'), indent=2, ensure_ascii=False)};",
            "",
        ]
        out.write_text("\n".join(body), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {out}"))
