"""
NEP Excellence Awards 2026 - University Domain Models
Defines first-class University institutions and University Assessment sessions.
"""
from datetime import date
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class University(models.Model):
    """
    Authoritative University Entity.
    Guarantees that a University is represented as a distinct first-class domain entity,
    and is NOT represented as a College with a renamed label.
    """
    name = models.CharField(
        max_length=255,
        help_text=_("Official registered name of the University.")
    )
    aishe_code = models.CharField(
        max_length=50,
        unique=True,
        db_index=True,
        help_text=_("Official AISHE code (e.g., U-0123) or University Registration Code.")
    )
    university_type = models.CharField(
        max_length=100,
        default="State Public University",
        help_text=_("Classification: State Public University, Deemed, Private, etc.")
    )
    state = models.CharField(
        max_length=100,
        default="Haryana",
        help_text=_("Jurisdiction state.")
    )
    address = models.TextField(
        blank=True,
        default="",
        help_text=_("Campus postal address.")
    )
    contact_email = models.EmailField(
        blank=True,
        default="",
        help_text=_("Primary institutional nodal/contact email.")
    )
    contact_phone = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Primary contact phone number.")
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_("Indicates whether the University is active for award participation.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("University")
        verbose_name_plural = _("Universities")
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.aishe_code})"


class UniversityAssessment(models.Model):
    """
    Authoritative University Assessment session entity.
    Encapsulates institutional assessment metadata, statutory assessment window,
    and raw parameter inputs for U1–U20.
    """
    assessment_id = models.CharField(
        max_length=100,
        unique=True,
        db_index=True,
        help_text=_("Unique assessment identifier (e.g. ASSESS-2026-UNI-001).")
    )
    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE,
        related_name="assessments",
        help_text=_("University institution under assessment.")
    )
    framework = models.CharField(
        max_length=50,
        default="UNIVERSITY_2026",
        editable=False,
        db_index=True,
        help_text=_("Enforces framework isolation: UNIVERSITY_2026.")
    )
    academic_year = models.CharField(
        max_length=20,
        default="2025-26",
        help_text=_("Statutory academic year (2025-26).")
    )
    period_start = models.DateField(
        default=date(2025, 7, 1),
        help_text=_("Assessment window start date (1 July 2025).")
    )
    period_end = models.DateField(
        default=date(2026, 6, 30),
        help_text=_("Assessment window end date (30 June 2026).")
    )
    status = models.CharField(
        max_length=50,
        default="DRAFT",
        db_index=True,
        help_text=_("Lifecycle status: DRAFT, SUBMITTED, UNDER_REVIEW, FINALIZED.")
    )
    submitted_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_("Timestamp when assessment was formally submitted.")
    )
    parameter_data = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Structured raw parameter inputs for U1–U20.")
    )
    assigned_reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="assigned_university_assessments",
        help_text=_("Screening committee reviewer assigned to this assessment.")
    )
    certified_score = models.FloatField(
        null=True,
        blank=True,
        help_text=_("Authoritative final certified score generated by frozen scoring engine.")
    )
    certification_status = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Certification status: FINALIZABLE, BLOCKED, etc.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("University Assessment")
        verbose_name_plural = _("University Assessments")
        ordering = ["-created_at"]

    def __str__(self):
        return f"UniversityAssessment({self.assessment_id} - {self.university.name})"


class ImmutableUniversityRecordError(Exception):
    """Raised when an attempt is made to modify or delete an immutable audit or review record."""
    pass


class UniversityReviewAction(models.TextChoices):
    START_REVIEW = "START_REVIEW", _("Start Review")
    COMPLETE_REVIEW = "COMPLETE_REVIEW", _("Complete Review")
    RETURN_FOR_CORRECTION = "RETURN_FOR_CORRECTION", _("Return For Correction")
    BLOCK_REVIEW = "BLOCK_REVIEW", _("Block Review")
    EVALUATE = "EVALUATE", _("Evaluate Scoring")
    CERTIFY = "CERTIFY", _("Certify Assessment")


class UniversityReviewRecord(models.Model):
    """
    Append-only historical record of committee review decisions and actions on a University Assessment.
    Guarantees that historical review outcomes, comments, and evaluation references are never overwritten.
    """
    review_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        db_index=True
    )
    assessment = models.ForeignKey(
        UniversityAssessment,
        on_delete=models.CASCADE,
        related_name="review_records",
        help_text=_("Associated University assessment.")
    )
    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="university_reviews",
        help_text=_("Committee reviewer or administrator who performed the review action.")
    )
    action = models.CharField(
        max_length=50,
        choices=UniversityReviewAction.choices,
        db_index=True,
        help_text=_("Action executed: START_REVIEW, COMPLETE_REVIEW, etc.")
    )
    status_before = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment lifecycle status prior to action.")
    )
    status_after = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("Assessment lifecycle status resulting from action.")
    )
    reason = models.TextField(
        blank=True,
        default="",
        help_text=_("Mandatory justification for corrections, blocks, or certification notes.")
    )
    comments = models.TextField(
        blank=True,
        default="",
        help_text=_("Reviewer notes or feedback for institution/committee.")
    )
    scoring_snapshot = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Authoritative snapshot of scoring evaluation at review time.")
    )
    evidence_readiness_snapshot = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Evidence readiness and coverage state snapshot at review time.")
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp when the review action was logged.")
    )

    class Meta:
        verbose_name = _("University Review Record")
        verbose_name_plural = _("University Review Records")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["assessment", "created_at"]),
            models.Index(fields=["reviewer", "action"]),
        ]

    def __str__(self):
        return f"ReviewRecord({self.assessment.assessment_id} - {self.action} by {self.reviewer.email})"

    def save(self, *args, **kwargs):
        if self.pk is not None:
            raise ImmutableUniversityRecordError("UniversityReviewRecord entries are append-only and cannot be modified.")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ImmutableUniversityRecordError("UniversityReviewRecord entries are audit logs and cannot be deleted.")


class UniversityAssessmentAuditLog(models.Model):
    """
    Append-only security and lifecycle audit log for all University assessment mutations.
    """
    log_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        db_index=True
    )
    assessment = models.ForeignKey(
        UniversityAssessment,
        on_delete=models.CASCADE,
        related_name="audit_logs",
        help_text=_("University assessment instance.")
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="university_audit_events",
        help_text=_("User or system actor initiating the action.")
    )
    action = models.CharField(
        max_length=50,
        db_index=True,
        help_text=_("Action type: REVIEW_STARTED, CERTIFICATION_ATTEMPTED, etc.")
    )
    previous_status = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("State before transition.")
    )
    new_status = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text=_("State after transition.")
    )
    outcome = models.CharField(
        max_length=30,
        default="SUCCESS",
        help_text=_("Outcome: SUCCESS, BLOCKED, FAILED.")
    )
    reason = models.TextField(
        blank=True,
        default="",
        help_text=_("Reason or explanation if applicable.")
    )
    payload = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Event-specific context, parameters, or blocking codes.")
    )
    timestamp = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text=_("Timestamp of the audit event.")
    )

    class Meta:
        verbose_name = _("University Assessment Audit Log")
        verbose_name_plural = _("University Assessment Audit Logs")
        ordering = ["-timestamp"]
        indexes = [
            models.Index(fields=["assessment", "timestamp"]),
            models.Index(fields=["action", "timestamp"]),
        ]

    def __str__(self):
        return f"AuditLog({self.action} on {self.assessment.assessment_id} at {self.timestamp})"

    def save(self, *args, **kwargs):
        if self.pk is not None:
            raise ImmutableUniversityRecordError("UniversityAssessmentAuditLog entries are append-only and cannot be modified.")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ImmutableUniversityRecordError("UniversityAssessmentAuditLog entries cannot be deleted.")
