# Generated by Django 6.0.6 on 2026-09-17 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official registered name of the University.', max_length=255)),
                ('aishe_code', models.CharField(db_index=True, help_text='Official AISHE code (e.g., U-0123) or University Registration Code.', max_length=50, unique=True)),
                ('university_type', models.CharField(default='State Public University', help_text='Classification: State Public University, Deemed, Private, etc.', max_length=100)),
                ('state', models.CharField(default='Haryana', help_text='Jurisdiction state.', max_length=100)),
                ('address', models.TextField(blank=True, default='', help_text='Campus postal address.')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Primary institutional nodal/contact email.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Primary contact phone number.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the University is active for award participation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(db_index=True, help_text='Unique assessment identifier (e.g. ASSESS-2026-UNI-001).', max_length=100, unique=True)),
                ('framework', models.CharField(db_index=True, default='UNIVERSITY_2026', editable=False, help_text='Enforces framework isolation: UNIVERSITY_2026.', max_length=50)),
                ('academic_year', models.CharField(default='2025-26', help_text='Statutory academic year (2025-26).', max_length=20)),
                ('period_start', models.DateField(default=datetime.date(2025, 7, 1), help_text='Assessment window start date (1 July 2025).')),
                ('period_end', models.DateField(default=datetime.date(2026, 6, 30), help_text='Assessment window end date (30 June 2026).')),
                ('status', models.CharField(db_index=True, default='DRAFT', help_text='Lifecycle status: DRAFT, SUBMITTED, UNDER_REVIEW, FINALIZED.', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when assessment was formally submitted.', null=True)),
                ('parameter_data', models.JSONField(blank=True, default=dict, help_text='Structured raw parameter inputs for U1–U20.')),
                ('certified_score', models.FloatField(blank=True, help_text='Authoritative final certified score generated by frozen scoring engine.', null=True)),
                ('certification_status', models.CharField(blank=True, default='', help_text='Certification status: FINALIZABLE, BLOCKED, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(help_text='University institution under assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='university.university')),
            ],
            options={
                'verbose_name': 'University Assessment',
                'verbose_name_plural': 'University Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
