# Generated by Django 6.0.6 on 2026-09-18 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='universityassessment',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Screening committee reviewer assigned to this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_university_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UniversityAssessmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, help_text='Action type: REVIEW_STARTED, CERTIFICATION_ATTEMPTED, etc.', max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', help_text='State before transition.', max_length=50)),
                ('new_status', models.CharField(blank=True, default='', help_text='State after transition.', max_length=50)),
                ('outcome', models.CharField(default='SUCCESS', help_text='Outcome: SUCCESS, BLOCKED, FAILED.', max_length=30)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason or explanation if applicable.')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event-specific context, parameters, or blocking codes.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the audit event.')),
                ('actor', models.ForeignKey(blank=True, help_text='User or system actor initiating the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_audit_events', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(help_text='University assessment instance.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='university.universityassessment')),
            ],
            options={
                'verbose_name': 'University Assessment Audit Log',
                'verbose_name_plural': 'University Assessment Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['assessment', 'timestamp'], name='university__assessm_1c8b21_idx'), models.Index(fields=['action', 'timestamp'], name='university__action_19e5d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversityReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('START_REVIEW', 'Start Review'), ('COMPLETE_REVIEW', 'Complete Review'), ('RETURN_FOR_CORRECTION', 'Return For Correction'), ('BLOCK_REVIEW', 'Block Review'), ('EVALUATE', 'Evaluate Scoring'), ('CERTIFY', 'Certify Assessment')], db_index=True, help_text='Action executed: START_REVIEW, COMPLETE_REVIEW, etc.', max_length=50)),
                ('status_before', models.CharField(blank=True, default='', help_text='Assessment lifecycle status prior to action.', max_length=50)),
                ('status_after', models.CharField(blank=True, default='', help_text='Assessment lifecycle status resulting from action.', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Mandatory justification for corrections, blocks, or certification notes.')),
                ('comments', models.TextField(blank=True, default='', help_text='Reviewer notes or feedback for institution/committee.')),
                ('scoring_snapshot', models.JSONField(blank=True, default=dict, help_text='Authoritative snapshot of scoring evaluation at review time.')),
                ('evidence_readiness_snapshot', models.JSONField(blank=True, default=dict, help_text='Evidence readiness and coverage state snapshot at review time.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the review action was logged.')),
                ('assessment', models.ForeignKey(help_text='Associated University assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='university.universityassessment')),
                ('reviewer', models.ForeignKey(help_text='Committee reviewer or administrator who performed the review action.', on_delete=django.db.models.deletion.PROTECT, related_name='university_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Review Record',
                'verbose_name_plural': 'University Review Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment', 'created_at'], name='university__assessm_b12ab5_idx'), models.Index(fields=['reviewer', 'action'], name='university__reviewe_7a2434_idx')],
            },
        ),
    ]
