# Generated by Django 6.0.6 on 2026-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('principal', 'College Principal'), ('admin', 'DHE Admin'), ('committee', 'Screening Committee'), ('committee_chair', 'Screening Committee Chair'), ('nodal_officer', 'University Nodal Officer'), ('university_admin', 'University Administrator')], default='principal', max_length=20),
        ),
    ]
