# Generated by Django 6.0.6 on 2026-09-16 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nominations', '0003_clarificationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable, immutable unique identifier for the evidence document.', unique=True)),
                ('assessment_id', models.CharField(db_index=True, help_text='Authoritative assessment session ID to which this evidence belongs.', max_length=100)),
                ('framework', models.CharField(db_index=True, help_text='Framework isolation identifier: UNIVERSITY_2026 or COLLEGE_2026.', max_length=50)),
                ('institution_type', models.CharField(db_index=True, help_text='Institution type: UNIVERSITY or COLLEGE.', max_length=50)),
                ('institution_id', models.CharField(db_index=True, help_text='Identifier of the institution (e.g., AISHE code or University ID).', max_length=100)),
                ('original_filename', models.CharField(help_text='Original file name as provided during upload.', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', help_text='Storage reference/key to document media (not binary DB blob).', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', help_text='MIME / Content type of the file.', max_length=100)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes.')),
                ('file_checksum', models.CharField(db_index=True, help_text='SHA-256 cryptographic hex digest of document bytes.', max_length=64)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when evidence was uploaded.')),
                ('evidence_type', models.CharField(db_index=True, help_text='Controlled evidence type identifier (e.g. EVID_U4_IDP, EVID_GENERAL).', max_length=100)),
                ('document_date', models.DateField(blank=True, help_text='Actual date of the activity/record. MUST NOT substitute upload or HOI date.', null=True)),
                ('academic_year', models.CharField(blank=True, db_index=True, help_text='Optional academic year relevance (e.g. 2024-25, 2025-26).', max_length=20, null=True)),
                ('status', models.CharField(choices=[('EVIDENCE_PRESENT', 'Evidence Present / Uploaded'), ('EVIDENCE_PENDING', 'Pending Verification'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_SUPERSEDED', 'Evidence Superseded'), ('EVIDENCE_WITHDRAWN', 'Evidence Withdrawn')], db_index=True, default='EVIDENCE_PRESENT', help_text='Current lifecycle state.', max_length=30)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of the document across supersessions.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible audit metadata.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if this is the active document (superseded/withdrawn = False).')),
                ('nomination', models.ForeignKey(blank=True, help_text='Optional link to existing Nomination record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_documents', to='nominations.nomination')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Pointer to the newer evidence document that superseded this one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_documents', to='evidence.evidencedocument')),
                ('uploader', models.ForeignKey(help_text='Identity of the user who uploaded the evidence.', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Document',
                'verbose_name_plural': 'Evidence Documents',
            },
        ),
        migrations.CreateModel(
            name='EvidenceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('assessment_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('UPLOADED', 'Evidence Uploaded'), ('SUBMITTED', 'Submitted For Verification'), ('VERIFIED', 'Verification Approved'), ('REJECTED', 'Verification Rejected'), ('SUPERSEDED', 'Evidence Superseded'), ('WITHDRAWN', 'Evidence Withdrawn'), ('ASSOCIATED', 'Associated to Subcriterion'), ('DISASSOCIATED', 'Disassociated from Subcriterion'), ('METADATA_UPDATED', 'Metadata Updated')], max_length=30)),
                ('previous_state', models.CharField(blank=True, default='', max_length=30)),
                ('new_state', models.CharField(blank=True, default='', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_audit_events', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Evidence Audit Log',
                'verbose_name_plural': 'Evidence Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSubcriterionAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('parameter_id', models.CharField(db_index=True, help_text='Parameter ID, e.g. U4, C1', max_length=50)),
                ('subcriterion_id', models.CharField(db_index=True, help_text='Subcriterion ID, e.g. U4.1, U4.A, C1.1', max_length=50)),
                ('response_id', models.CharField(blank=True, default='', help_text='Optional specific response identifier', max_length=100)),
                ('academic_year', models.CharField(blank=True, default='', help_text='Academic year context of this association', max_length=20)),
                ('associated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('associated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_associations', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='evidence.evidencedocument')),
            ],
            options={
                'verbose_name': 'Evidence Subcriterion Association',
                'verbose_name_plural': 'Evidence Subcriterion Associations',
            },
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review')], max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Mandatory justification for rejections; optional remarks for verifications.')),
                ('previous_state', models.CharField(choices=[('EVIDENCE_PRESENT', 'Evidence Present / Uploaded'), ('EVIDENCE_PENDING', 'Pending Verification'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_SUPERSEDED', 'Evidence Superseded'), ('EVIDENCE_WITHDRAWN', 'Evidence Withdrawn')], max_length=30)),
                ('resulting_state', models.CharField(choices=[('EVIDENCE_PRESENT', 'Evidence Present / Uploaded'), ('EVIDENCE_PENDING', 'Pending Verification'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_SUPERSEDED', 'Evidence Superseded'), ('EVIDENCE_WITHDRAWN', 'Evidence Withdrawn')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='evidence.evidencedocument')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Verification',
                'verbose_name_plural': 'Evidence Verifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['assessment_id', 'framework'], name='evidence_ev_assessm_f4ce57_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['file_checksum'], name='evidence_ev_file_ch_1702db_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['status', 'is_active'], name='evidence_ev_status_7e5b69_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceauditlog',
            index=models.Index(fields=['evidence', 'timestamp'], name='evidence_ev_evidenc_0ae7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='evidence_ev_action_a953aa_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesubcriterionassociation',
            index=models.Index(fields=['parameter_id', 'subcriterion_id'], name='evidence_ev_paramet_a318c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencesubcriterionassociation',
            constraint=models.UniqueConstraint(fields=('evidence', 'parameter_id', 'subcriterion_id'), name='unique_active_evidence_subcriterion_association'),
        ),
        migrations.AddIndex(
            model_name='evidenceverification',
            index=models.Index(fields=['evidence', 'timestamp'], name='evidence_ev_evidenc_9e9801_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceverification',
            index=models.Index(fields=['decision', 'verifier'], name='evidence_ev_decisio_a664e7_idx'),
        ),
    ]
