# Generated by Django 6.0.6 on 2026-09-17 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('nominations', '0003_clarificationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REVOKED', 'Revoked'), ('REASSIGNED', 'Reassigned')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evidence Review Assignment',
                'verbose_name_plural': 'Evidence Review Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('framework', models.CharField(db_index=True, help_text='Authorized framework: UNIVERSITY_2026, COLLEGE_2026, or ALL.', max_length=50)),
                ('institution_id', models.CharField(blank=True, db_index=True, default='', help_text='Optional specific institution scope (e.g. AISHE code). If blank, applies to all institutions in framework.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if this authorization is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Reviewer Authorization',
                'verbose_name_plural': 'Reviewer Authorizations',
            },
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when evidence was assigned to reviewer.', null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who assigned the reviewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Screening committee reviewer assigned to verify this evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evidence_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenceverification',
            name='inspected_checksum',
            field=models.CharField(blank=True, default='', help_text='Cryptographic SHA-256 hash inspected and verified by the reviewer.', max_length=64),
        ),
        migrations.AddField(
            model_name='evidenceverification',
            name='inspected_version',
            field=models.PositiveIntegerField(default=1, help_text='Document version inspected by the reviewer.'),
        ),
        migrations.AddField(
            model_name='evidenceverification',
            name='rejection_code',
            field=models.CharField(blank=True, default='', help_text='Machine-readable structured rejection code (RejectionReasonCode).', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidenceauditlog',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Evidence Uploaded'), ('SUBMITTED', 'Submitted For Verification'), ('VERIFIED', 'Verification Approved'), ('REJECTED', 'Verification Rejected'), ('SUPERSEDED', 'Evidence Superseded'), ('WITHDRAWN', 'Evidence Withdrawn'), ('ASSOCIATED', 'Associated to Subcriterion'), ('DISASSOCIATED', 'Disassociated from Subcriterion'), ('METADATA_UPDATED', 'Metadata Updated'), ('ASSIGNED', 'Reviewer Assigned'), ('UNASSIGNED', 'Reviewer Unassigned'), ('REASSIGNED', 'Reviewer Reassigned')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='evidencedocument',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='evidence_ev_assigne_b9b43a_idx'),
        ),
        migrations.AddField(
            model_name='evidencereviewassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencereviewassignment',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='evidence.evidencedocument'),
        ),
        migrations.AddField(
            model_name='evidencereviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerauthorization',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerauthorization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidencereviewassignment',
            index=models.Index(fields=['evidence', 'status'], name='evidence_ev_evidenc_a666e2_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencereviewassignment',
            index=models.Index(fields=['reviewer', 'status'], name='evidence_ev_reviewe_30c5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerauthorization',
            index=models.Index(fields=['user', 'framework', 'is_active'], name='evidence_re_user_id_6f95d3_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewerauthorization',
            index=models.Index(fields=['framework', 'institution_id'], name='evidence_re_framewo_f31b01_idx'),
        ),
    ]
