# Generated by Django 6.0.6 on 2026-09-24 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_verification_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubcriterionassociation',
            name='claim_description',
            field=models.TextField(blank=True, default='', help_text="Institution's claim or explanation of how this document region supports this subcriterion."),
        ),
        migrations.AddField(
            model_name='evidencesubcriterionassociation',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, help_text='Ending page for composite document supporting this subcriterion.', null=True),
        ),
        migrations.AddField(
            model_name='evidencesubcriterionassociation',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, help_text='Starting page for composite document supporting this subcriterion.', null=True),
        ),
        migrations.AddField(
            model_name='evidencesubcriterionassociation',
            name='section_identifier',
            field=models.CharField(blank=True, default='', help_text='Specific section, table, or annexure identifier inside the document.', max_length=100),
        ),
        migrations.AddField(
            model_name='evidencesubcriterionassociation',
            name='subcriterion_evidence_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The exact evidence type claimed for this subcriterion (e.g. EVID_U7_APPOINTMENT).', max_length=100),
        ),
        migrations.CreateModel(
            name='EvidenceAssociationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable, immutable unique identifier for this association verification.', unique=True)),
                ('decision', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review')], default='PENDING', help_text='Auditable verification decision: PENDING, VERIFIED, or REJECTED.', max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Reviewer notes, remarks, or mandatory justification for rejections.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this association verification record was created.')),
                ('inspected_checksum', models.CharField(blank=True, default='', help_text='Cryptographic SHA-256 hash of the evidence document inspected by the reviewer.', max_length=64)),
                ('rejection_code', models.CharField(blank=True, default='', help_text='Structured, machine-readable rejection code (RejectionReasonCode) when rejected.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible audit metadata.')),
                ('association', models.ForeignKey(help_text='Evidence subcriterion association being verified.', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='evidence.evidencesubcriterionassociation')),
                ('verifier', models.ForeignKey(help_text='Identity of reviewer who evaluated this association.', on_delete=django.db.models.deletion.PROTECT, related_name='association_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Association Verification',
                'verbose_name_plural': 'Evidence Association Verifications',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['association', 'timestamp'], name='evidence_ev_associa_eab6f0_idx'), models.Index(fields=['decision', 'verifier'], name='evidence_ev_decisio_a3fdbe_idx')],
            },
        ),
    ]
