# Generated by Django 6.0.6 on 2026-09-18 15:40

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(db_index=True, help_text='Unique assessment identifier (e.g. ASSESS-2026-COL-001).', max_length=100, unique=True)),
                ('framework', models.CharField(db_index=True, default='COLLEGE_2026', editable=False, help_text='Enforces framework isolation: COLLEGE_2026.', max_length=50)),
                ('academic_year', models.CharField(default='2025-26', help_text='Statutory academic year (2025-26).', max_length=20)),
                ('period_start', models.DateField(default=datetime.date(2025, 7, 1), help_text='Assessment window start date (1 July 2025).')),
                ('period_end', models.DateField(default=datetime.date(2026, 6, 30), help_text='Assessment window end date (30 June 2026).')),
                ('status', models.CharField(db_index=True, default='DRAFT', help_text='Lifecycle status: DRAFT, SUBMITTED, UNDER_REVIEW, FINALIZED.', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when assessment was formally submitted.', null=True)),
                ('parameter_data', models.JSONField(blank=True, default=dict, help_text='Structured raw parameter inputs for C1–C22.')),
                ('certified_score', models.FloatField(blank=True, help_text='Authoritative final certified score generated by frozen scoring engine.', null=True)),
                ('certification_status', models.CharField(blank=True, default='', help_text='Certification status: FINALIZABLE, BLOCKED, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, help_text='Screening committee reviewer assigned to this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_college_assessments', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(help_text='College institution under assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='authentication.college')),
            ],
            options={
                'verbose_name': 'College Assessment',
                'verbose_name_plural': 'College Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeAssessmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, help_text='Action executed (e.g. CREATED, PARAMETER_UPDATED, SUBMITTED).', max_length=50)),
                ('previous_state', models.CharField(blank=True, default='', help_text='Assessment status before the action.', max_length=50)),
                ('new_state', models.CharField(blank=True, default='', help_text='Assessment status after the action.', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional rationale or note for the action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the audit event occurred.')),
                ('actor', models.ForeignKey(blank=True, help_text='Actor who initiated the assessment state change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_assessment_audit_events', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(help_text='Associated College assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='college.collegeassessment')),
            ],
            options={
                'verbose_name': 'College Assessment Audit Log',
                'verbose_name_plural': 'College Assessment Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
