# Generated by Django 6.0.6 on 2026-09-18 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('START_REVIEW', 'Start Review'), ('COMPLETE_REVIEW', 'Complete Review'), ('RETURN_FOR_CORRECTION', 'Return For Correction'), ('BLOCK_REVIEW', 'Block Review'), ('EVALUATE', 'Evaluate Scoring'), ('CERTIFY', 'Certify Assessment')], db_index=True, help_text='Action executed: START_REVIEW, COMPLETE_REVIEW, etc.', max_length=50)),
                ('status_before', models.CharField(blank=True, default='', help_text='Assessment lifecycle status prior to action.', max_length=50)),
                ('status_after', models.CharField(blank=True, default='', help_text='Assessment lifecycle status resulting from action.', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Mandatory justification for corrections, blocks, or certification notes.')),
                ('comments', models.TextField(blank=True, default='', help_text='Reviewer notes or feedback for institution/committee.')),
                ('scoring_snapshot', models.JSONField(blank=True, default=dict, help_text='Authoritative snapshot of scoring evaluation at review time.')),
                ('evidence_readiness_snapshot', models.JSONField(blank=True, default=dict, help_text='Evidence readiness and coverage state snapshot at review time.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the review action was logged.')),
                ('assessment', models.ForeignKey(help_text='Associated College assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='college.collegeassessment')),
                ('reviewer', models.ForeignKey(help_text='Committee reviewer or administrator who performed the review action.', on_delete=django.db.models.deletion.PROTECT, related_name='college_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Review Record',
                'verbose_name_plural': 'College Review Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assessment', 'created_at'], name='college_col_assessm_c25295_idx'), models.Index(fields=['reviewer', 'action'], name='college_col_reviewe_d53725_idx')],
            },
        ),
    ]
