# Generated by Django 6.0.5 on 2026-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_collegereviewrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeassessment',
            name='status',
            field=models.CharField(db_index=True, default='DRAFT', help_text='Lifecycle status: DRAFT, SUBMITTED, UNDER_REVIEW, CERTIFIED, REJECTED.', max_length=50),
        ),
    ]
