"""
NEP Excellence Awards 2026 - Parameter & Subcriterion Definitions
Authoritative configuration derived strictly from NEP_2026_PARAMETER_SPECIFICATION.md
"""
from typing import Any, Dict

from apps.scoring.enums import (
    DoubleCountingRule,
    EvaluationType,
    FrameworkType,
    PeriodRule,
    ResolutionStatus,
    ThresholdOperator,
)

UNIVERSITY_PARAMETERS: Dict[str, Dict[str, Any]] = {
    "U1": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U1",
        "title": "Apprenticeship Embedded Degree Programmes",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U1_APPROVAL"],
        "subcriteria": {
            "U1.1": {
                "subcriterion_code": "U1.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 10.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 7.0, "max_val": 10.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 4.0, "max_val": 7.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 0.0, "max_val": 4.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "U2": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U2",
        "title": "Courses Offered in Indian Languages",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U2_COURSE_LIST"],
        "subcriteria": {
            "U2.1": {
                "subcriterion_code": "U2.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 75.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 0.0, "max_val": 25.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "U3": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U3",
        "title": "Integration of Indian Knowledge Systems (IKS)",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U3_SYLLABUS"],
        "subcriteria": {
            "U3.1": {
                "subcriterion_code": "U3.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 25.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 15.0, "max_val": 25.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 5.0, "max_val": 15.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 0.0, "max_val": 5.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "U4": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U4",
        "title": "Targets Achieved under Institutional Development Plan (IDP)",
        "max_marks": 6.0,
        "period_rule": PeriodRule.MULTI_PERIOD,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "allowed_evidence": ["EVID_U4_IDP", "EVID_U4_TARGET_SHEET", "EVID_U4_PROGRESS_REPORT"],
        "subcriteria": {
            "U4.A": {
                "subcriterion_code": "U4.A",
                "title": "IDP targets fixed for 2024-25",
                "max_score": 3.0,
                "mandatory_evidence": ["EVID_U4_PROGRESS_REPORT"],
                "allowed_evidence": ["EVID_U4_IDP", "EVID_U4_TARGET_SHEET", "EVID_U4_PROGRESS_REPORT"],
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            },
            "U4.B": {
                "subcriterion_code": "U4.B",
                "title": "IDP targets fixed for 2025-26",
                "max_score": 3.0,
                "mandatory_evidence": ["EVID_U4_PROGRESS_REPORT"],
                "allowed_evidence": ["EVID_U4_IDP", "EVID_U4_TARGET_SHEET", "EVID_U4_PROGRESS_REPORT"],
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            },
            "U4.1": {
                "subcriterion_code": "U4.1",
                "title": "IDP targets fixed for 2024-25",
                "max_score": 3.0,
                "mandatory_evidence": ["EVID_U4_PROGRESS_REPORT"],
                "allowed_evidence": ["EVID_U4_IDP", "EVID_U4_TARGET_SHEET", "EVID_U4_PROGRESS_REPORT"],
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            },
            "U4.2": {
                "subcriterion_code": "U4.2",
                "title": "IDP targets fixed for 2025-26",
                "max_score": 3.0,
                "mandatory_evidence": ["EVID_U4_PROGRESS_REPORT"],
                "allowed_evidence": ["EVID_U4_IDP", "EVID_U4_TARGET_SHEET", "EVID_U4_PROGRESS_REPORT"],
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            },
        },
    },
    "U5": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U5",
        "title": "Percentage of Students Who Received Placement / Pre-Placement Offers",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.BOUNDARY_UNRESOLVED,
        "mandatory_evidence": ["EVID_U5_HOI_CERT"],
        "subcriteria": {
            "U5.A": {
                "subcriterion_code": "U5.A",
                "title": "Placement Eligibility Rate",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 50.0, "score": 0.0},
                ],
                "boundary_voids": [
                    {"exact_val": 50.0, "reason": "U5.A: Source text omits rule for exactly 50.0% (>50% vs <50%). BOUNDARY_UNRESOLVED."}
                ],
            },
            "U5.B": {
                "subcriterion_code": "U5.B",
                "title": "Placement Conversion Rate",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 0.5},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 25.0, "score": 0.0},
                ],
            },
        },
    },
    "U6": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U6",
        "title": "Academic Reforms",
        "max_marks": 8.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U6_ORDINANCE_GAZETTE"],
        "subcriteria": {
            "U6.A": {"subcriterion_code": "U6.A", "max_score": 4.0},
            "U6.B": {"subcriterion_code": "U6.B", "max_score": 4.0},
        },
    },
    "U7": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U7",
        "title": "Professor of Practice (PoP) Engagement",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U7_APPOINTMENT"],
        "subcriteria": {
            "U7.1": {"subcriterion_code": "U7.1", "max_score": 1.0},
            "U7.2": {"subcriterion_code": "U7.2", "max_score": 1.0},
            "U7.3": {"subcriterion_code": "U7.3", "max_score": 1.0},
            "U7.4": {"subcriterion_code": "U7.4", "max_score": 1.0},
        },
    },
    "U8": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U8",
        "title": "Incubation / Startup Cell Performance as per NISP",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.COMPOSITE,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U8_INCUBATION_REG"],
        "subcriteria": {
            "U8.A": {
                "subcriterion_code": "U8.A",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 10.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 6.0, "max_val": 10.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 1.0, "max_val": 5.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            },
            "U8.B": {
                "subcriterion_code": "U8.B",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 50.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 50.0, "score": 0.0},
                ],
            },
        },
    },
    "U9": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U9",
        "title": "Academic / Research Collaboration with Foreign HEIs",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.COMPOSITE,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U9_MOU"],
        "subcriteria": {
            "U9.A": {
                "subcriterion_code": "U9.A",
                "max_score": 1.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 75.0, "score": 0.0},
                ],
            },
            "U9.B": {
                "subcriterion_code": "U9.B",
                "max_score": 5.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 5.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 4.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 3.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 2.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 1.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            },
        },
    },
    "U10": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U10",
        "title": "Functional Alumni Connect Cell",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.BOUNDARY_UNRESOLVED,
        "mandatory_evidence": ["EVID_U10_REG_CERT"],
        "subcriteria": {
            "U10.1": {"subcriterion_code": "U10.1", "max_score": 1.0},
            "U10.2": {"subcriterion_code": "U10.2", "max_score": 1.0},
            "U10.3": {
                "subcriterion_code": "U10.3",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                    {"operator": ThresholdOperator.OP_GT, "min_val": 10000000.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LT, "min_val": 0.0, "max_val": 10000000.0, "score": 1.0},
                ],
                "boundary_voids": [
                    {"exact_val": 10000000.0, "reason": "U10.3: Source text omits rule for exactly Rs. 1 Crore (>1Cr vs <1Cr). BOUNDARY_UNRESOLVED."}
                ],
            },
            "U10.4": {"subcriterion_code": "U10.4", "max_score": 1.0},
        },
    },
    "U11": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U11",
        "title": "Gender Parity Initiatives",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U11_BOARDS"],
        "subcriteria": {
            "U11.1": {"subcriterion_code": "U11.1", "max_score": 1.0},
            "U11.2": {"subcriterion_code": "U11.2", "max_score": 1.0},
            "U11.3": {"subcriterion_code": "U11.3", "max_score": 1.0},
            "U11.4": {"subcriterion_code": "U11.4", "max_score": 1.0},
        },
    },
    "U12": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U12",
        "title": "Physical Fitness, Sports, Yoga, Health, Welfare, Psychological Well-being",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U12_CENTRE_NOTIF"],
        "subcriteria": {
            "U12.1": {"subcriterion_code": "U12.1", "max_score": 1.0},
            "U12.2": {"subcriterion_code": "U12.2", "max_score": 1.0},
            "U12.3": {"subcriterion_code": "U12.3", "max_score": 1.0},
            "U12.4": {"subcriterion_code": "U12.4", "max_score": 1.0},
            "U12.5": {"subcriterion_code": "U12.5", "max_score": 1.0},
        },
    },
    "U13": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U13",
        "title": "Online Courses / MOOCs Policy and Adoption",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U13_POLICY"],
        "subcriteria": {
            "U13.1": {
                "subcriterion_code": "U13.1",
                "max_score": 6.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 75.0, "score": 6.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 0.0, "max_val": 25.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "U14": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U14",
        "title": "Multidisciplinary Education",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.REQUIRES_FRAMEWORK_EXCEPTION,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U14_CURRICULUM"],
        "subcriteria": {
            "U14.A": {
                "subcriterion_code": "U14.A",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 25.0, "score": 0.0},
                ],
            },
            "U14.B": {"subcriterion_code": "U14.B", "max_score": 1.0},
            "U14.C": {"subcriterion_code": "U14.C", "max_score": 1.0},
        },
    },
    "U15": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U15",
        "title": "Multiple Entry-Exit Operationalized",
        "max_marks": 2.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U15_ORDINANCE"],
        "subcriteria": {
            "U15.1": {"subcriterion_code": "U15.1", "max_score": 1.0},
            "U15.2": {"subcriterion_code": "U15.2", "max_score": 1.0},
        },
    },
    "U16": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U16",
        "title": "Research Outcome: Patents Filed and Granted",
        "max_marks": 8.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
        "mandatory_evidence": ["EVID_U16_FILING"],
        "subcriteria": {
            "U16.I": {
                "subcriterion_code": "U16.I",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 10.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 5.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 5.0, "score": 0.0},
                ],
            },
            "U16.II": {
                "subcriterion_code": "U16.II",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 2.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 1.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 1.0, "score": 0.0},
                ],
            },
            "U16.III": {
                "subcriterion_code": "U16.III",
                "max_score": 4.0,
                "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
                "unresolved_reason": "Scopus Index is not a standard defined scalar metric in authoritative source.",
            },
        },
    },
    "U17": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U17",
        "title": "Registration and Performance in NIRF",
        "max_marks": 2.0,
        "period_rule": PeriodRule.REFERENCE_YEAR_DEPENDENT,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U17_NIRF_2026_PROOF"],
        "subcriteria": {
            "U17.1": {"subcriterion_code": "U17.1", "max_score": 1.0},
            "U17.2": {"subcriterion_code": "U17.2", "max_score": 1.0},
        },
    },
    "U18": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U18",
        "title": "Recognition of Prior Learning (RPL) Adoption and Implementation",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U18_POLICY"],
        "subcriteria": {
            "U18.1": {"subcriterion_code": "U18.1", "max_score": 1.0},
            "U18.2": {"subcriterion_code": "U18.2", "max_score": 1.0},
            "U18.3": {"subcriterion_code": "U18.3", "max_score": 2.0},
        },
    },
    "U19": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U19",
        "title": "Adoption of Outcome-Based Education (OBE)",
        "max_marks": 8.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_U19_OBE_FRAMEWORK"],
        "subcriteria": {
            "U19.A": {
                "subcriterion_code": "U19.A",
                "max_score": 6.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 6.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 80.0, "max_val": 90.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 70.0, "max_val": 80.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 60.0, "max_val": 70.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 60.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 25.0, "score": 0.0},
                ],
            },
            "U19.B": {"subcriterion_code": "U19.B", "max_score": 2.0},
        },
    },
    "U20": {
        "framework": FrameworkType.UNIVERSITY_2026,
        "parameter_code": "U20",
        "title": "Activities Aligned with Sustainable Development Goals (SDGs)",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.SOURCE_INCONSISTENCY,
        "unresolved_reason": "Source items sum to 5 marks against declared 4 marks maximum.",
        "mandatory_evidence": ["EVID_U20_ACTIVITY_REPORTS"],
        "subcriteria": {
            "U20.1": {
                "subcriterion_code": "U20.1",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 10.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 5.0, "max_val": 9.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 5.0, "score": 0.0},
                ],
            },
            "U20.2": {"subcriterion_code": "U20.2", "max_score": 2.0},
            "U20.3": {"subcriterion_code": "U20.3", "max_score": 1.0},
        },
    },
}

COLLEGE_PARAMETERS: Dict[str, Dict[str, Any]] = {
    "C1": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C1",
        "title": "Institutional Development Plan (IDP) and NEP Implementation Targets",
        "max_marks": 6.0,
        "period_rule": PeriodRule.REFERENCE_YEAR_DEPENDENT,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C1_APPROVED_IDP"],
        "subcriteria": {
            "C1.1": {
                "subcriterion_code": "C1.1",
                "max_score": 6.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 6.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 1.0},
                ],
            }
        },
    },
    "C2": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C2",
        "title": "Apprenticeship / Internships",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C2_HOI_CERT"],
        "subcriteria": {
            "C2.1": {
                "subcriterion_code": "C2.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 25.0, "max_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 25.0, "score": 0.0},
                ],
            }
        },
    },
    "C3": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C3",
        "title": "Academic Bank of Credits (ABC) Registration",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_INSENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C3_ABC_DASHBOARD"],
        "subcriteria": {
            "C3.1": {
                "subcriterion_code": "C3.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 60.0, "max_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 60.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            }
        },
    },
    "C4": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C4",
        "title": "Supporting Other Institutes and Schools in Their Development",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C4_INSTITUTE_CERTS"],
        "subcriteria": {
            "C4.A": {"subcriterion_code": "C4.A", "max_score": 2.0},
            "C4.B": {"subcriterion_code": "C4.B", "max_score": 2.0},
        },
    },
    "C5": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C5",
        "title": "Student Enrollment against Sanctioned Seats",
        "max_marks": 2.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.BOUNDARY_UNRESOLVED,
        "mandatory_evidence": ["EVID_C5_SANCTION_LETTER"],
        "subcriteria": {
            "C5.1": {
                "subcriterion_code": "C5.1",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LT, "min_val": 75.0, "max_val": 90.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 75.0, "score": 0.0},
                ],
                "boundary_voids": [
                    {"exact_val": 75.0, "reason": "C5.1: Source text omits rule for exactly 75.0% (>75% and <90% vs <75%). BOUNDARY_UNRESOLVED."}
                ],
            }
        },
    },
    "C6": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C6",
        "title": "VAC, AEC, SEC, NSQF-Aligned Courses and Short-Term Certifications",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C6_COURSE_APPROVAL"],
        "subcriteria": {
            "C6.1": {
                "subcriterion_code": "C6.1",
                "max_score": 6.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 6.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 80.0, "max_val": 90.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 70.0, "max_val": 80.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 60.0, "max_val": 70.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 60.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 1.0},
                ],
            }
        },
    },
    "C7": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C7",
        "title": "Bridge Courses for SEDGs",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
        "unresolved_reason": "C7 has declared maximum 6 marks but visible rubric tiers sum to 3 marks (-3 mark deficit).",
        "mandatory_evidence": ["EVID_C7_OFFICE_ORDERS"],
        "subcriteria": {
            "C7.1": {
                "subcriterion_code": "C7.1",
                "max_score": 3.0,  # Visible rubric tiers top out at 3 marks
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 75.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 50.0, "score": 0.0},
                ],
            }
        },
    },
    "C8": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C8",
        "title": "Nomination of NEP-SARTHI",
        "max_marks": 2.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
        "unresolved_reason": "C8 has declared maximum 2 marks but only a single unquantified textual line in source.",
        "mandatory_evidence": ["EVID_C8_OFFICE_ORDERS"],
        "subcriteria": {
            "C8.1": {"subcriterion_code": "C8.1", "max_score": 2.0},
        },
    },
    "C9": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C9",
        "title": "Student Career Orientation and Placements",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C9_FAIR_REGISTER"],
        "subcriteria": {
            "C9.I": {
                "subcriterion_code": "C9.I",
                "max_score": 3.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 100.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 50.0, "score": 0.0},
                ],
            },
            "C9.II": {
                "subcriterion_code": "C9.II",
                "max_score": 3.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 100.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 75.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 50.0, "score": 0.0},
                ],
            },
        },
    },
    "C10": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C10",
        "title": "Industry Collaboration, MoUs and Industry-Aligned Academic Activities",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C10_MOU_DOCS"],
        "subcriteria": {
            "C10.1": {
                "subcriterion_code": "C10.1",
                "max_score": 5.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 5.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 4.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 3.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 2.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 1.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "C11": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C11",
        "title": "Incubation, Startup Cell and Entrepreneurship Promotion",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C11_REGISTRATION"],
        "subcriteria": {
            "C11.I": {
                "subcriterion_code": "C11.I",
                "max_score": 3.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 10.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 6.0, "max_val": 10.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 1.0, "max_val": 5.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            },
            "C11.II.a": {"subcriterion_code": "C11.II.a", "max_score": 1.0},
            "C11.II.b": {
                "subcriterion_code": "C11.II.b",
                "max_score": 1.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 50.0, "score": 0.0},
                ],
            },
        },
    },
    "C12": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C12",
        "title": "Alumni Connect and External Expert Engagement",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C12_DATABASE"],
        "subcriteria": {
            "C12.1": {"subcriterion_code": "C12.1", "max_score": 1.0},
            "C12.2": {"subcriterion_code": "C12.2", "max_score": 1.0},
            "C12.3": {"subcriterion_code": "C12.3", "max_score": 1.0},
            "C12.4": {"subcriterion_code": "C12.4", "max_score": 1.0},
            "C12.5": {"subcriterion_code": "C12.5", "max_score": 1.0},
        },
    },
    "C13": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C13",
        "title": "Faculty Development and NEP Orientation",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C13_FDP_CERTS"],
        "subcriteria": {
            "C13.1": {
                "subcriterion_code": "C13.1",
                "max_score": 4.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 80.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 60.0, "max_val": 80.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 40.0, "max_val": 60.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 20.0, "max_val": 40.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LTE, "max_val": 20.0, "score": 0.0},
                ],
            }
        },
    },
    "C14": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C14",
        "title": "Indian Languages and Indian Knowledge System (IKS)",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C14_MATERIAL_CERT"],
        "subcriteria": {
            "C14.A": {"subcriterion_code": "C14.A", "max_score": 2.0},
            "C14.B": {"subcriterion_code": "C14.B", "max_score": 2.0},
        },
    },
    "C15": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C15",
        "title": "Student Well-being, Physical Fitness, Yoga and Sports",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C15_CENTRE_ORDER"],
        "subcriteria": {
            "C15.1": {"subcriterion_code": "C15.1", "max_score": 1.0},
            "C15.2": {"subcriterion_code": "C15.2", "max_score": 1.0},
            "C15.3": {"subcriterion_code": "C15.3", "max_score": 1.0},
            "C15.4": {"subcriterion_code": "C15.4", "max_score": 1.0},
            "C15.5": {"subcriterion_code": "C15.5", "max_score": 1.0},
            "C15.6": {"subcriterion_code": "C15.6", "max_score": 1.0},
        },
    },
    "C16": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C16",
        "title": "Gender Parity, Safety and Inclusion Initiatives",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.FIXED_ITEM_SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
        "unresolved_reason": "C16 has declared maximum 4 marks but lists 5 distinct 1-mark items (+1 mark excess).",
        "mandatory_evidence": ["EVID_C16_ICC_ORDERS"],
        "subcriteria": {
            "C16.1": {"subcriterion_code": "C16.1", "max_score": 1.0},
            "C16.2": {"subcriterion_code": "C16.2", "max_score": 1.0},
            "C16.3": {"subcriterion_code": "C16.3", "max_score": 1.0},
            "C16.4": {"subcriterion_code": "C16.4", "max_score": 1.0},
            "C16.5": {"subcriterion_code": "C16.5", "max_score": 1.0},
        },
    },
    "C17": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C17",
        "title": "Outreach, Community Engagement and Social Responsibility",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.MAX,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C17_STUDENT_LIST"],
        "subcriteria": {
            "C17.1": {
                "subcriterion_code": "C17.1",
                "max_score": 5.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GT, "min_val": 90.0, "score": 5.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 75.0, "max_val": 90.0, "score": 4.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 60.0, "max_val": 75.0, "score": 3.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 50.0, "max_val": 60.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GT_AND_LTE, "min_val": 0.0, "max_val": 50.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            }
        },
    },
    "C18": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C18",
        "title": "Sustainable Development Goals (SDGs), Green Campus and Environmental Practices",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C18_ACTIVITY_REPORTS"],
        "subcriteria": {
            "C18.1": {"subcriterion_code": "C18.1", "max_score": 2.0},
            "C18.2": {"subcriterion_code": "C18.2", "max_score": 1.0},
            "C18.3": {"subcriterion_code": "C18.3", "max_score": 1.0},
            "C18.4": {"subcriterion_code": "C18.4", "max_score": 1.0},
        },
    },
    "C19": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C19",
        "title": "Research, Innovation and Patents",
        "max_marks": 6.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
        "mandatory_evidence": ["EVID_C19_FILING_CERTS"],
        "subcriteria": {
            "C19.I": {
                "subcriterion_code": "C19.I",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 4.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 2.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 2.0, "score": 0.0},
                ],
            },
            "C19.II": {
                "subcriterion_code": "C19.II",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 2.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 1.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 1.0, "score": 0.0},
                ],
            },
            "C19.III": {
                "subcriterion_code": "C19.III",
                "max_score": 2.0,
                "resolution_status": ResolutionStatus.UNRESOLVED_RULE,
                "unresolved_reason": "Scopus Index is not a standard defined scalar metric in authoritative source.",
            },
        },
    },
    "C20": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C20",
        "title": "Quality Assurance, NAAC/NIRF/AISHE and Institutional Reporting",
        "max_marks": 5.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C20_NAAC_CERT"],
        "subcriteria": {
            "C20.1": {
                "subcriterion_code": "C20.1",
                "max_score": 2.0,
                "tier_1_grades": ["A++", "A+", "A", "B++"],
                "tier_2_grades": ["B+", "B"],
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 2.0, "score": 2.0},  # A++, A+, A, B++ -> 2
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 1.0, "score": 1.0},   # B, B+ -> 1
                    {"operator": ThresholdOperator.OP_EQ, "target_val": 0.0, "score": 0.0},
                ],
            },
            "C20.2": {"subcriterion_code": "C20.2", "max_score": 1.0},
            "C20.3": {"subcriterion_code": "C20.3", "max_score": 1.0},
            "C20.4": {"subcriterion_code": "C20.4", "max_score": 1.0},
        },
    },
    "C21": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C21",
        "title": "Cultural Activities, Constitutional Values and Holistic Development",
        "max_marks": 4.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.SOURCE_INCONSISTENCY,
        "unresolved_reason": "Source items sum to 3 marks against declared 4 marks maximum.",
        "mandatory_evidence": ["EVID_C21_ACTIVITY_REPORTS"],
        "subcriteria": {
            "C21.1": {
                "subcriterion_code": "C21.1",
                "max_score": 2.0,
                "thresholds": [
                    {"operator": ThresholdOperator.OP_GTE, "min_val": 10.0, "score": 2.0},
                    {"operator": ThresholdOperator.OP_GTE_AND_LTE, "min_val": 5.0, "max_val": 9.0, "score": 1.0},
                    {"operator": ThresholdOperator.OP_LT, "max_val": 5.0, "score": 0.0},
                ],
            },
            "C21.2": {"subcriterion_code": "C21.2", "max_score": 1.0},
        },
    },
    "C22": {
        "framework": FrameworkType.COLLEGE_2026,
        "parameter_code": "C22",
        "title": "Governance, Student Feedback and Evidence-Based Improvement",
        "max_marks": 2.0,
        "period_rule": PeriodRule.PERIOD_SENSITIVE,
        "aggregation_strategy": EvaluationType.SUM,
        "double_counting_rule": DoubleCountingRule.FORBIDDEN_REUSE,
        "resolution_status": ResolutionStatus.CALCULABLE,
        "mandatory_evidence": ["EVID_C22_NODAL_ORDER"],
        "subcriteria": {
            "C22.1": {"subcriterion_code": "C22.1", "max_score": 1.0},
            "C22.2": {"subcriterion_code": "C22.2", "max_score": 1.0},
        },
    },
}
